#!/usr/bin/env python

shopping_list = ["banana", "orange", "apple"]

stock = {
        "banana": 6, 
        "apple": 0, 
        "orange": 32,
        "peaar": 15
        }

prices = {
    "banana": 4,
    "apple": 2,
    "orange": 1.5,
    }

# Write your code below!
def compute_bill(food):
    total = 0
    for item in food:
        if stock[item] > 0:
            total = prices[item] + total
            stock[item] = stock[item] - 1

    return total

print "The function 'compute bill(food)' takes in a list of foods and \n\
        computes the total price by add the price of the item to \n\
        'total' and reduces stock by one for that item."
print "foods: ", shopping_list
print "computed bill:  ", compute_bill(shopping_list)


